version: '3.9'

services:
  app:
    build:
      context: ./build/app
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: spotweb-app
    depends_on:
      - mailpit
      - mariadb
    restart: always
    user: ${UID:-1000}:${GID:-1000}
    networks:
      - worker
    volumes:
      - ./src:/src:rw,z,U
    x-podman:
      uidmaps:
        - "0:1:1"
        - "${UID:-1000}:0:1"
      gidmaps:
        - "0:1:1"
        - "${GID:-1000}:0:1"
  nginx:
    build:
      context: ./build/nginx
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: spotweb-nginx
    depends_on:
      - app
    restart: always
    user: ${UID:-1000}:${GID:-1000}
    working_dir: /src
    networks:
      - worker
      - web
    ports:
      - 81:8080
      - 444:4443
    volumes:
      - ./ssl:/ssl:ro,Z
      - ./src:/src:ro,z
    secrets:
      - source: ssl-cert
        target: cert.pem
      - source: ssl-key
        target: key.pem
      - source: ssl-dhparam
        target: dhparam.pem
    x-podman:
      uidmaps:
        - "0:1:1"
        - "${UID:-1000}:0:1"
      gidmaps:
        - "0:1:1"
        - "${GID:-1000}:0:1"
  mariadb:
    image: mariadb:latest
    container_name: spotweb-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_TCP_PORT: 3307
    restart: always
    networks:
      - worker
    ports:
      - 3307:3307
    volumes:
      - mariadb:/var/lib/mysql:rw,Z
  mailpit:
    image: axllent/mailpit:latest
    container_name: spotweb-mailpit
    restart: always
    networks:
      - worker
    ports:
      - 1026:1025
      - 8026:8025
secrets:
  ssl-cert:
    file: ./ssl/cert.pem
  ssl-key:
    file: ./ssl/key.pem
  ssl-dhparam:
    file: ./ssl/dhparam.pem
volumes:
  mariadb:
    name: spotweb-mariadb
networks:
  worker:
    internal: true
  web:
